@startuml ComponentesEntities
skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome false
skinparam linetype ortho
skinparam nodesep 70
skinparam ranksep 80

title Diagrama de Componentes de Entidades

component "RocketFactory" as Factory <<Patrón Creacional>>
component "Motor Box2D" as Box2D <<Físicas Externas>>

package "Entidades Dinámicas" {
    component "PlayerCar" as Player <<Vehículo>>
    component "Bosses IA" as Bosses <<Antagonistas>>
    component "Ball" as Ball <<Elemento Reactivo>>
}

' Dependencias de creación
Factory ..> Player : <<instantiate>>
Factory ..> Bosses : <<instantiate>>
Factory ..> Ball : <<instantiate>>

' Dependencias físicas (Sincronización)
Player ..down..> Box2D : <<update physics>>\n[b2Body / Fuerzas]
Bosses ..down..> Box2D : <<update physics>>\n[b2Body / Fuerzas]
Ball ..down..> Box2D : <<update physics>>\n[b2Body / Rebotes]

@enduml