@startuml ArquitecturaScenes
skinparam shadowing false
skinparam monochrome false
skinparam classAttributeIconSize 0
skinparam linetype ortho
' Forzamos distancias cortas para que el diagrama sea compacto
skinparam nodesep 30
skinparam ranksep 30

title Jerarquía de Escenas

package "Core (Motor)" {
    class Director {
        - scene_stack: list
        + apilarEscena(scene: Scene): void
    }

    abstract class Scene {
        # director: Director
        + update(dt: float): void
        + render(screen: Surface): void
    }

    class PyGameScene {
        - is_overlay: boolean
        - fade_alpha: float
        + fade_to_black(): void
    }
}

' Relaciones principales
Director "1" *-- "0..*" Scene
Scene "0..*" o-- "1" Director
Scene <|-- PyGameScene

package "Interfaces" {
    class Menu
    class SettingsScene
    class IngameMenu
}

PyGameScene <|-- Menu
PyGameScene <|-- SettingsScene
PyGameScene <|-- IngameMenu

package "Narrativa" {
    class DialogueScene {
        - manager: DialogueManager
    }
    class CreditsScene
}

' Forzado de columna: Narrativa debajo de Interfaces
Interfaces -[hidden]down- Narrativa
PyGameScene <|-- DialogueScene
PyGameScene <|-- CreditsScene

package "Jugabilidad (Match)" {
    class MatchScene {
        # score_left: int
        + _draw_hud(screen: Surface): void
    }

    class FirstScene
    class SecondScene
    class ThirdScene
}

' Forzado de columna: Jugabilidad debajo de Narrativa
Narrativa -[hidden]down- "Jugabilidad (Match)"
PyGameScene <|-- MatchScene

' Herencia de niveles
MatchScene <|-- FirstScene
MatchScene <|-- SecondScene
MatchScene <|-- ThirdScene

@enduml