@startuml ArquitecturaScenes
' Forzamos modo diagrama de clases
skinparam shadowing false
skinparam monochrome false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 40

title UML de la Jerarquía de Escenas 

package "Core (Motor)" {
    class Director {
        - scene_stack: list
        + apilarEscena(scene: Scene): void
        + cambiarEscena(scene: Scene): void
        + exitScene(): void
    }

    abstract class Scene {
        # director: Director
        + update(dt: float): void
        + events(ev: list): void
        + render(screen: Surface): void
    }

    class PyGameScene {
        - is_overlay: boolean
        - fade_alpha: float
        + fade_to_black(): void
        + fade_from_black(): void
    }
}

' --- RELACIONES DE PROPIEDAD Y USO ---
Director "1" *-- "0..*" Scene : Gestiona
Scene "0..*" o-- "1" Director : Referencia
Scene <|-- PyGameScene

package "Interfaces" {
    class Menu {
        - screenList: list
    }
    class SettingsScene
    class IngameMenu
}

' Herencias simples
PyGameScene <|-- Menu
PyGameScene <|-- SettingsScene
PyGameScene <|-- IngameMenu

package "Narrativa" {
    class DialogueScene {
        - manager: DialogueManager
    }
    class CreditsScene
}

' Separación vertical para que no se amontone
Interfaces -[hidden]down- Narrativa
PyGameScene <|-- DialogueScene
PyGameScene <|-- CreditsScene

package "Jugabilidad (Match)" {
    class MatchScene {
        # score_left: int
        # score_right: int
        + _draw_hud(screen: Surface): void
    }

    class FirstScene
    class SecondScene
    class ThirdScene
}

' Herencia de segundo nivel
Narrativa -[hidden]down- "Jugabilidad (Match)"
PyGameScene <|-- MatchScene
MatchScene <|-- FirstScene
MatchScene <|-- SecondScene
MatchScene <|-- ThirdScene

@enduml