@startuml DialogueSystem
title Dialogue System — Estructura y Flujo Narrativo

' CLASSES
class DialogueScene <<PyGameScene>> {
    + __init__(director, json_path)
    + _load_characters()
    + _spawn_current_bubble()
    + update (dt)
    + _update_fx_logic(dt_sec)
    + render (screen)
    + events (events)
    + _start_exit_transition()
    + _handle_flash(data)
    + _handle_shake(data)
    + _handle_wait(data)
    + _stop_all_audio()
}

class DialogueManager {
    + __init__(json_path)
    + _load()
    + set_speed_multiplier(multiplier)
    + current_line()
    + update(dt)
    + get_shown_text()
    + is_line_complete()
    + advance()
    + get_current_speaker_state()
    + get_current_events()
}

class DialogueUI {
    + __init__(json_path)
    + _anim_slide(rect, progress)
    + _anim_pop(rect, progress)
    + update_anim(dt)
    + draw(screen, y_pos, current_text, fixed_x, is_last, is_intro)
    + _draw_content(screen, rect, current_text, is_last)
    + _wrap_text(self, text, max_w)
    + get_expected_height()
}

class DialogueSoundPlayer {
    +__init__(config, volume)
    + set_interval_by_speed(speed)
    + reset()
    + play_check(char, speaker_name)
}

class Assets <<Singleton>> {
    - _IMAGE_DATA : dict
    - _SOUND_DATA : dict
    - _MUSIC_DATA : dict
    + get_image(key) : Surface
    + get_sound(key) : Sound
    + get_music_path(key) : String
}

' RELATIONSHIPS
DialogueScene "1" *-- "1" DialogueManager : controla
DialogueScene "1" *-- "1" DialogueUI : actualiza/dibuja
DialogueScene "1" *-- "1" DialogueSoundPlayer : dispara sonidos

DialogueUI ..> Assets : solicita recursos
DialogueSoundPlayer ..> Assets : solicita sonidos/música


@enduml